### ISSUE TITLE
Svelte - Input - dynamically switching type not working.

### ISSUE THREAD

**Issue by apiotrowski312** [AgnosticUI/agnosticui#114]
Hello! I have an issue with Input.

```
<script lang="ts">
	let textIsVisible = false;
	const toggleTextVisibility = () => {
		textIsVisible = !textIsVisible;
	};
</script>

...
<Input
	id={attributes.name}
	type={textIsVisible ? 'text' : 'password'}
	hasRightAddon={true}
>
	<div slot="addonRight">
		<InputAddonItem addonRight={true}>
			<button type="button" on:click={toggleTextVisibility}>
				{#if textIsVisible}
					<EyeOff />
				{:else}
					<Eye />
				{/if}
			</button>
		</InputAddonItem>
	</div>
</Input>
```

I had exactly same stuff coded with normal input and switching type is working as expected. In above example for some reason it is not. I am sure variable is changing as icon is changing.

I am using SvelteKit with svelte: 3.46.4 and agnostic-svelte version 1.1.3.

---
Update:

It is not working because of this function call, as it is called only on initialization. 
```
file: node_modules/agnostic-svelte/components/Input/Input.svelte

 <input
      ...
      type="{getInputType()}"
      ...
    />
```

I switched it to smth like this and it started working as expected. Not sure how proper fix would look like unfortunately. 
```
type={type}
```

**Comment by roblevintennis** [comment]
@apiotrowski312 that's a compelling use case :) Thanks for reporting and for the clarity in your code examples.

I was able to reproduce the issue and also found that binding directly the the `type` prop was required for it to work. 

Here's my fix:
https://github.com/AgnosticUI/agnosticui/commit/f28de49af82882b9a9e74966d1b4e90168be63cb#diff-f20d9256cc9e1f3267f44c304a04b6ede004724df67c20cf46279700179c2e3cR416

Can you possibly point your NPM package to `master` temporarily to try this out? I'm sure I'll cut another release soon, but I don't have a guaranteed ETA exactly.

Lmk if this unblocks you!

**Comment by roblevintennis** [comment]
Here's my "hooptie" repro with fix:

![image](https://user-images.githubusercontent.com/142403/157139330-c91171bb-c387-4ec7-82e4-cfd67672f622.png)

![Uploading image.png…]()

**Comment by apiotrowski312** [comment]
@roblevintennis Thank you! I do not need it right away, as I am working on pet projects, so no need to rush with it. Yes, I can point to master. 

One more time thank you for quick fix :3
