### ISSUE TITLE
typo in docs

### ISSUE THREAD

**Issue by longrunningprocess** [AgnosticUI/agnosticui#119]
http://www.agnosticui.com/docs/advanced/advanced-usage.html#modular-css-imports references `...reset...` but it's actually `resets`

![image](https://user-images.githubusercontent.com/4412848/157997725-6f36ed61-77a0-4ef7-93a7-fc4955d49982.png)

`"agnostic-svelte": "^1.1.6",`

**Comment by roblevintennis** [comment]
Thanks @longrunningprocess https://www.agnosticui.com/docs/advanced/advanced-usage.html is fixed now

**Comment by longrunningprocess** [comment]
I'm sorry Rob, I did that from my phone and obviously gave you the wrong link, it's in theming:  https://www.agnosticui.com/docs/theming.html#reset

![image](https://user-images.githubusercontent.com/4412848/158023178-4f015b8a-5e17-4ffe-aac4-7d6202c62357.png)

**Comment by longrunningprocess** [comment]
yes, thank you!

**Comment by roblevintennis** [comment]
@longrunningprocess https://developtodesign.com/agnosticui-examples has the Vest form example I was mentioning and links to the source code. Might be helpful

**Comment by longrunningprocess** [comment]
> @longrunningprocess https://developtodesign.com/agnosticui-examples has the Vest form example I was mentioning and links to the source code. Might be helpful

very slick and encouraging they stayed focused and cohesive on validation!
