### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by roblevintennis** [AgnosticUI/agnosticui#14]
Implementation may vary a bit from framework to framework but basically I see this designed as follows:

- We use a data attribute for light and dark respectively that we placed on the body tag
- We have a mapping of CSS custom properties with same names but different values for light and dark
- Those css property mappings are scoped to the corresponding light and dark attribute scheme that's in fact placed on the body tag
- We use local storage to store the last selected mode
- When loading we check first to see if there's a local storage mode preference set. If so, we use that, if not we check the users operating system reserves color check

**Comment by roblevintennis** [comment]
Adam Argyles excellent tutorials may prove helpful here:
[transcript]([https://goo.gle/3qGhnt7](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqblBtOXZBRXNDTEttODFaTVFvMjR0SDJKMHRJUXxBQ3Jtc0trd2poNUJSb3ZXZnJoUS1SS0cyMjFEbWhzelhQMFRHOVBOUzl6NGFjcGFCY0VzZ1I4WWFBMURjNGQ2NWZNY0ZQdjZWWUZMcFk5c1BCemFxZHRsaXB0alVxTGVIZFRLbUNYTHBZY09VdnJ4bUpQLXJwbw&q=https%3A%2F%2Fgoo.gle%2F3qGhnt7))
[demo]([https://goo.gle/3GMUfig](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbEpqMlVoRFNnU0hUV044UTFpWk9sdDBUSWpmQXxBQ3Jtc0ttM0RRUERaUkdsNVFiMkh3T0xQNHAzdkZFcDlucGVQTHVGRVFsQWgxS0dWQlJ0Ql93VlRKNURoYkIzbFZnb1B4VjhSZERGRy1Xbi1qTmFZMFVhVVFJdkxtMDhmbjBEdDNGSWhUN2VvU1lmOWpSbFhQbw&q=https%3A%2F%2Fgoo.gle%2F3GMUfig))

[source]([https://goo.gle/3rz8VLv](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbklMNS1vMmxtTEpLRUV6cm5vV3hWMm1uSkVQd3xBQ3Jtc0tuVWdMdF9wQ0ptZ25qY21qUkI4d2xMVWQ0elF5R3FnZFdDWUdPNnYyZno5UlJpakxyTVo3UkhURmtsSHU0TVpWVHVWY2RqSE1neUxJMmlmaVpVZWl5RkZCanRLTk1rS25FVkQzMi1Sek1ycG0wUnAxMA&q=https%3A%2F%2Fgoo.gle%2F3rz8VLv))

**Comment by roblevintennis** [comment]
First part done: https://github.com/AgnosticUI/agnosticui/pull/228

Second part will be:

- First checks local storage. If not set uses OS settings. If not set defaults to light mode
- Add a toggle button (moon / sun) to toggle user's color preferences
- Update sites: Vue 3 Docs (Done), Astro Docs (hackathon), and finally the Site Docs

**Comment by nikhilyeole1** [comment]
Great to see dark mode support coming soon. I am very much influenced by agnostic UI philosophy. I was searching for similar approach and landed here. 
Looking forward to contribute once I get some time.

**Comment by roblevintennis** [comment]
@nikhilyeole1 thanks so much!!

I believe I already have dark mode support in `master` but I'm not certain I've deployed updates to NPM yet. I got sort of swamped with things. Lmk if you are blocked by this.
