### ISSUE TITLE
Precommit bugs

### ISSUE THREAD

**Issue by roblevintennis** [AgnosticUI/agnosticui#154]
It's been reported there's some bugs with the precommit hooks and it's blocking contributors https://github.com/AgnosticUI/agnosticui/issues/140#issuecomment-1094089637

I need to get this fixed asap

**Comment by vitale232** [comment]
As a workaround, I was able to just nuke it:

```shell
rm -rf .husky
```

Don't tell my pooch ;-)

**Comment by gcsecsey** [comment]
All subprojects are linted even if there are no relevant changes. Also, the the `prettier` script is missing in `agnostic-svelte`, which causes this step to fail. In #156 I've updated the precommit hook to run lint-staged instead, which seems to work nicely as a temporary solution.

I'm also working on a more well-rounded solution, that'd run the appropriate lint and format tasks in only those subprojects which contains changes.

**Comment by roblevintennis** [comment]
Thanks for contributing this hotfix @gcsecsey I'm going to preemptively close this as DONE (but will test a bit later today -- gotta run at the moment).

🙏
