### ISSUE TITLE
JSDoc

### ISSUE THREAD

**Issue by Croug** [AgnosticUI/agnosticui#176]
We should create a JSDoc with with detailed information on each of the component properties, to be used in conjunction with the existing examples. Putting this here for future tracking. 

Not sure if you have a better way to track progress on these or have a different template, if you do let me know and I'll swap it out, otherwise we could potentially use this as a template in the future for overarching projects like this

### Alerts

- [ ] React
- [ ] Vue
- [ ] Svelte
- [ ] Angular

### Avatars

- [ ] React
- [ ] Vue
- [ ] Svelte
- [ ] Angular

### Breadcrumbs

- [ ] React
- [ ] Vue
- [ ] Svelte
- [ ] Angular

### Buttons

- [ ] React
- [ ] Vue
- [ ] Svelte
- [ ] Angular

### Cards

- [ ] React
- [ ] Vue
- [ ] Svelte
- [ ] Angular

### Choices

- [ ] React
- [ ] Vue
- [ ] Svelte
- [ ] Angular

### Close

- [ ] React
- [ ] Vue
- [ ] Svelte
- [ ] Angular

### Dialog

- [ ] React
- [ ] Vue
- [ ] Svelte
- [ ] Angular

### Disclose

- [ ] React
- [ ] Vue
- [ ] Svelte
- [ ] Angular

### Divider

- [ ] React
- [ ] Vue
- [ ] Svelte
- [ ] Angular

### Drawer

- [ ] React
- [ ] Vue
- [ ] Svelte
- [ ] Angular

### EmptyState

- [ ] React
- [ ] Vue
- [ ] Svelte
- [ ] Angular

### Header

- [ ] React
- [ ] Vue
- [ ] Svelte
- [ ] Angular

### Icons

- [ ] React
- [ ] Vue
- [ ] Svelte
- [ ] Angular

### Inputs

- [ ] React
- [ ] Vue
- [ ] Svelte
- [ ] Angular

### Loader

- [ ] React
- [ ] Vue
- [ ] Svelte
- [ ] Angular

### Menu

- [ ] React
- [ ] Vue
- [ ] Svelte
- [ ] Angular

### Pagination

- [ ] React
- [ ] Vue
- [ ] Svelte
- [ ] Angular

### Progress

- [ ] React
- [ ] Vue
- [ ] Svelte
- [ ] Angular

### Select

- [ ] React
- [ ] Vue
- [ ] Svelte
- [ ] Angular

### Spinner

- [ ] React
- [ ] Vue
- [ ] Svelte
- [ ] Angular

### Switch

- [ ] React
- [ ] Vue
- [ ] Svelte
- [ ] Angular

### Table

- [ ] React
- [ ] Vue
- [ ] Svelte
- [ ] Angular

### Tabs

- [ ] React
- [ ] Vue
- [ ] Svelte
- [ ] Angular

### Tags

- [ ] React
- [ ] Vue
- [ ] Svelte
- [ ] Angular

### Toasts

- [ ] React
- [ ] Vue
- [ ] Svelte
- [ ] Angular

**Comment by roblevintennis** [comment]
Thanks! I think the checkboxes makes sense 👍🏽

I would like to delve into the goals a bit.

- No doubt we should document component properties 
- But how?
- If we used jsdoc to generate html site where does that go?
- Would it be possible to integrate into the Vitepress docs site (AgnosticUI dot com) or would it need to be hosted separately?
- If the later, would we link from the main docs to these generated jsdoc based ones? How?


I'm keen on the overall goal but I just want to understand all above first. We could keep the dialogue async here in comments or catch up on Gitter which maybe better I dunno.

**Comment by Croug** [comment]
Yeah this absolutely needs a lot more discussion, and I don't think it's something either of us will get to right away, just figured I'd put it here so it's something that we're thinking about, as I know it's something I was looking for when I first found the project, I think we don't need to have a place to go to the overall docs on the site, but definitely link to each component under it's respective framework in the current docs
