### ISSUE TITLE
[Svelte] Table wont update on new data when sorted

### ISSUE THREAD

**Issue by Croug** [AgnosticUI/agnosticui#193]
**Describe the bug**
In Svelte when new data is provided for the table while it is sorted, instead of the new data rendering, it renders the old data

**To Reproduce**
1. Create a table with data
2. Sort any of the columns
3. Provide the table with new data

**Expected behavior**
The table should render the new data

**Comment by roblevintennis** [comment]
Good find 👍🏽

Should this be an opt-in prop? I could see a case for one time eagerly loaded data where you may not want the data fully reloaded each time. Thoughts?

**Comment by Croug** [comment]
So how would that look? In my mind, if you don't want to reload the data you would manage that yourself by controlling what data goes into the rows property, but maybe I'm missing a use case here

**Comment by roblevintennis** [comment]
Ok per our discussion we won't worry about the edge case I mentioned and as you put it that's probably something the consumer can control anyway. THanks for thinking that through with me and helping me understand. PR merge so closing this out -- as always thank you so much of your contributions @Croug
