### ISSUE TITLE
Review workspace settings

### ISSUE THREAD

**Issue by gcsecsey** [AgnosticUI/agnosticui#202]
**Describe the bug**
Looking at `.vscode/settings.json`, there are numerous workspace settings that change the basic look & feel of the editor. As these settings have no effect on the code pushed to the repo, IMO these should be set on the user level instead of the workspace level.

**To Reproduce**

Looking at some settings in `.vscode/settings.json`:

- These settings only affect the UI of VSCode:
  ```json
  {
    "editor.fontSize": 15,
    "editor.tabSize": 2,
    "editor.suggestSelection": "first",
    "editor.minimap.enabled": false,
  }
  ```
- These settings are nice to have on the workspace level, but I think should be up to user preference. We should instead rely on pre-commit hooks and code validation on a CI/CD pipeline (eg. via GH actions) to enforce linting/formatting rules:
  ```json
  {
    "editor.formatOnSave": true,
    "eslint.validate": [
      "javascript",
      "javascriptreact",
      // [Error - 9:45:52 PM] Error: Error while loading rule '@nrwl/nx/enforce-module-boundaries': ENOENT: no such file or directory, open '/Users/roblevin/workspace/opensource/agnosticui/nx.json'
      //   "typescript",
      "typescriptreact"
    ],  
    "editor.codeActionsOnSave": {
      "source.fixAll.eslint": true
    },
  }
  ```
- These settings reference plugins which aren't necessarily installed on any contributor's machines. We could add plugins that are required to work with the repo as [workspace recommended extensions](https://code.visualstudio.com/docs/editor/extension-marketplace#_workspace-recommended-extensions), so that VSCode offers to install these automatically:
  ```json
  {
    "webhint.enableTelemetry": "disabled",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue"
  }
  ```
- These settings can be overridden when formatting is run from the command line (eslint or prettier):
  ```json
  {
    "html.format.wrapAttributes": "force-aligned",
    "[html]": {
      "editor.defaultFormatter": "vscode.html-language-features"
    },
    "vetur.format.defaultFormatter.html": "js-beautify-html",
    "[vue]": {
      "editor.defaultFormatter": "octref.vetur"
    }
  }
  ```

**Expected behavior**

We should strive to enforce linting/formatting rules on the server side, and/or in pre-commit hooks. This would make contributing to the project easier with other IDEs and independent of IDE settings.

**Comment by roblevintennis** [comment]
I agree with all you've said. For now what's the recommendation exactly? Delete the vscode config and add to gitignore?

**Comment by gcsecsey** [comment]
I'm not sure whether we should delete the whole config. For the editor settings, we can go ahead and remove the setting, but for  others, it would be better to substitute them with the appropriate git hook or GH action.

I can go over each setting and raise a PR with the easy ones removed, and some others replaced, lmk if that's OK. 🙂

**Comment by roblevintennis** [comment]
Thanks 🙏🏽 @gcsecsey that makes sense!
