### ISSUE TITLE
[astro] Cannot find module or its corresponding type declarations

### ISSUE THREAD

**Issue by jlsnow301** [AgnosticUI/agnosticui#241]
**Describe the bug**
On a completely stock installation of astro v1.2.4 (the current version as of this post), cannot use components as expected from the agnostic-astro package. Throws compile and runtime errors that packages cannot be found or are not exported.

Here is a repo which throws the below screenshot:
https://github.com/jlsnow301/agnostic-astro-test

**To Reproduce**
1. ```yarn create astro```
2. cd to folder
3. ```yarn add agnostic-astro```
4. Attempt to use one of the components

**Expected behavior**
Install astro, install agnostic-astro, then use components like 
```import AgButton from "agnostic-astro"```
```<AgButton>Something</AgButton>```

**Screenshots**
![Screenshot 2022-09-14 140236](https://user-images.githubusercontent.com/42397676/190261861-1e74cb94-1033-4903-8855-5c465e97eaa7.png)
![Screenshot 2022-09-14 141025](https://user-images.githubusercontent.com/42397676/190263128-3bb61500-fdb1-43b2-b9b3-e5901ff3b481.png)

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser: Brave
 - Version: 1.43.89

**Issues with pull requests are deeply appreciated! But sometimes it's worth discussing first so the implementation works with AgnosticUI guidelines**

**Comment by roblevintennis** [comment]
Thanks for this thorough ticket -- I'll look into next spare cycle I have!
