### ISSUE TITLE
Document CDN Usage

### ISSUE THREAD

**Issue by roblevintennis** [AgnosticUI/agnosticui#42]
`cd site && yarn docs:dev` -- http://localhost:3009/docs/setup.html#cdn --- nothing there yet -- need to verify unpkg for all frameworks and create tests/examples then document

Add jsDelivr too
Looks like it picked up the npm:

https://www.jsdelivr.com/package/npm/agnostic-vue

**Comment by jimaek** [comment]
Consider using jsDelivr too, you would also get detailed download stats per file and per version :)

**Comment by roblevintennis** [comment]
Unfortunately, Vue 3 UMD is not working properly in my tests 🙁 as the Vue props of Type Boolean are not getting updated and I wasn't able to track down the root cause. This is unfortunate. Might try with ES6 modules and CDN for browsers that support 🤷🏽‍♂️

**Comment by roblevintennis** [comment]
Going to punt on the whole browser / umd stuff for now and recommend ES modules setup via NPM. Will revisit later
