### ISSUE TITLE
Svelte Tabs

### ISSUE THREAD

**Issue by roblevintennis** [AgnosticUI/agnosticui#53]
The Svelte tabs were working fine in Storybook, but when I added them to the example application at `agnostic-svelte/examples/src/App.svelte` the `tabButtonRefs` bindings don't appear to be populated on mount...they do oddly if I click once on a tab button.

Keeping an eye on: https://github.com/sveltejs/svelte/issues/6919 which may help I dunno

**Comment by rmunn** [comment]
I believe this will probably be fixed by https://github.com/sveltejs/svelte/pull/6920 once that gets merged.

**Comment by roblevintennis** [comment]
Thanks @rmunn -- I appreciate that you stopped by to mention (and thanks for your PR efforts upstream as well!)

**Comment by roblevintennis** [comment]
Tried to bump svelte to `"svelte": "3.44.3"` and got a bunch of `index.js:470 Uncaught TypeError: Cannot read property '$$' of undefined` errors no matter how stripped down my examples app was. Might need to wait to try again.

**Comment by roblevintennis** [comment]
If I could figure out how to install a fresh directory w/latest svelte I'd be game to try to copy over components one at a time if that helps (as painful as it'd be)

**Comment by roblevintennis** [comment]
I'm completly revamping agnostic-svelte with a latest svelte-kit install (and it's resolving to `3.46.2` (well passed the PR that was merged) and I'm "pretty sure" it's now working 🚀 🙌  -- need to do a lot more testing and refactoring before I start celebrating, but without even digging into source code I can keyboard navigate these same tabs so I'm feeling pretty good about this.
